services:
  - type: web
    name: Movie_Discovery_App
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npx nodemon
    envVars:
      - key: NODE_ENV
        value: production
